// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arch-state.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_arch_2dstate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_arch_2dstate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_arch_2dstate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_arch_2dstate_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_arch_2dstate_2eproto;
class ArchState;
class ArchStateDefaultTypeInternal;
extern ArchStateDefaultTypeInternal _ArchState_default_instance_;
class BasicCSR;
class BasicCSRDefaultTypeInternal;
extern BasicCSRDefaultTypeInternal _BasicCSR_default_instance_;
class CSR;
class CSRDefaultTypeInternal;
extern CSRDefaultTypeInternal _CSR_default_instance_;
class MisaCSR;
class MisaCSRDefaultTypeInternal;
extern MisaCSRDefaultTypeInternal _MisaCSR_default_instance_;
class SatpCSR;
class SatpCSRDefaultTypeInternal;
extern SatpCSRDefaultTypeInternal _SatpCSR_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ArchState* Arena::CreateMaybeMessage<::ArchState>(Arena*);
template<> ::BasicCSR* Arena::CreateMaybeMessage<::BasicCSR>(Arena*);
template<> ::CSR* Arena::CreateMaybeMessage<::CSR>(Arena*);
template<> ::MisaCSR* Arena::CreateMaybeMessage<::MisaCSR>(Arena*);
template<> ::SatpCSR* Arena::CreateMaybeMessage<::SatpCSR>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CSR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CSR) */ {
 public:
  CSR();
  virtual ~CSR();

  CSR(const CSR& from);
  CSR(CSR&& from) noexcept
    : CSR() {
    *this = ::std::move(from);
  }

  inline CSR& operator=(const CSR& from) {
    CopyFrom(from);
    return *this;
  }
  inline CSR& operator=(CSR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CSR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSR* internal_default_instance() {
    return reinterpret_cast<const CSR*>(
               &_CSR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CSR& a, CSR& b) {
    a.Swap(&b);
  }
  inline void Swap(CSR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CSR* New() const final {
    return CreateMaybeMessage<CSR>(nullptr);
  }

  CSR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CSR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CSR& from);
  void MergeFrom(const CSR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CSR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arch_2dstate_2eproto);
    return ::descriptor_table_arch_2dstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgAddrFieldNumber = 1,
    kMsgCsrPrivFieldNumber = 2,
    kMsgCsrReadOnlyFieldNumber = 3,
  };
  // uint64 msg_addr = 1;
  void clear_msg_addr();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_addr() const;
  void set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_addr() const;
  void _internal_set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 msg_csr_priv = 2;
  void clear_msg_csr_priv();
  ::PROTOBUF_NAMESPACE_ID::uint32 msg_csr_priv() const;
  void set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_msg_csr_priv() const;
  void _internal_set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool msg_csr_read_only = 3;
  void clear_msg_csr_read_only();
  bool msg_csr_read_only() const;
  void set_msg_csr_read_only(bool value);
  private:
  bool _internal_msg_csr_read_only() const;
  void _internal_set_msg_csr_read_only(bool value);
  public:

  // @@protoc_insertion_point(class_scope:CSR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_addr_;
  ::PROTOBUF_NAMESPACE_ID::uint32 msg_csr_priv_;
  bool msg_csr_read_only_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arch_2dstate_2eproto;
};
// -------------------------------------------------------------------

class BasicCSR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BasicCSR) */ {
 public:
  BasicCSR();
  virtual ~BasicCSR();

  BasicCSR(const BasicCSR& from);
  BasicCSR(BasicCSR&& from) noexcept
    : BasicCSR() {
    *this = ::std::move(from);
  }

  inline BasicCSR& operator=(const BasicCSR& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicCSR& operator=(BasicCSR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BasicCSR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BasicCSR* internal_default_instance() {
    return reinterpret_cast<const BasicCSR*>(
               &_BasicCSR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BasicCSR& a, BasicCSR& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicCSR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BasicCSR* New() const final {
    return CreateMaybeMessage<BasicCSR>(nullptr);
  }

  BasicCSR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BasicCSR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BasicCSR& from);
  void MergeFrom(const BasicCSR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicCSR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BasicCSR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arch_2dstate_2eproto);
    return ::descriptor_table_arch_2dstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgAddrFieldNumber = 1,
    kMsgCsrPrivFieldNumber = 2,
    kMsgCsrReadOnlyFieldNumber = 3,
    kMsgValFieldNumber = 4,
  };
  // uint64 msg_addr = 1;
  void clear_msg_addr();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_addr() const;
  void set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_addr() const;
  void _internal_set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 msg_csr_priv = 2;
  void clear_msg_csr_priv();
  ::PROTOBUF_NAMESPACE_ID::uint32 msg_csr_priv() const;
  void set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_msg_csr_priv() const;
  void _internal_set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool msg_csr_read_only = 3;
  void clear_msg_csr_read_only();
  bool msg_csr_read_only() const;
  void set_msg_csr_read_only(bool value);
  private:
  bool _internal_msg_csr_read_only() const;
  void _internal_set_msg_csr_read_only(bool value);
  public:

  // uint64 msg_val = 4;
  void clear_msg_val();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_val() const;
  void set_msg_val(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_val() const;
  void _internal_set_msg_val(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:BasicCSR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_addr_;
  ::PROTOBUF_NAMESPACE_ID::uint32 msg_csr_priv_;
  bool msg_csr_read_only_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_val_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arch_2dstate_2eproto;
};
// -------------------------------------------------------------------

class MisaCSR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MisaCSR) */ {
 public:
  MisaCSR();
  virtual ~MisaCSR();

  MisaCSR(const MisaCSR& from);
  MisaCSR(MisaCSR&& from) noexcept
    : MisaCSR() {
    *this = ::std::move(from);
  }

  inline MisaCSR& operator=(const MisaCSR& from) {
    CopyFrom(from);
    return *this;
  }
  inline MisaCSR& operator=(MisaCSR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MisaCSR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MisaCSR* internal_default_instance() {
    return reinterpret_cast<const MisaCSR*>(
               &_MisaCSR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MisaCSR& a, MisaCSR& b) {
    a.Swap(&b);
  }
  inline void Swap(MisaCSR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MisaCSR* New() const final {
    return CreateMaybeMessage<MisaCSR>(nullptr);
  }

  MisaCSR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MisaCSR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MisaCSR& from);
  void MergeFrom(const MisaCSR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MisaCSR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MisaCSR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arch_2dstate_2eproto);
    return ::descriptor_table_arch_2dstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgBasicCsrFieldNumber = 1,
    kMsgMaxIsaFieldNumber = 2,
    kMsgWriteMaskFieldNumber = 3,
  };
  // .BasicCSR msg_basic_csr = 1;
  bool has_msg_basic_csr() const;
  private:
  bool _internal_has_msg_basic_csr() const;
  public:
  void clear_msg_basic_csr();
  const ::BasicCSR& msg_basic_csr() const;
  ::BasicCSR* release_msg_basic_csr();
  ::BasicCSR* mutable_msg_basic_csr();
  void set_allocated_msg_basic_csr(::BasicCSR* msg_basic_csr);
  private:
  const ::BasicCSR& _internal_msg_basic_csr() const;
  ::BasicCSR* _internal_mutable_msg_basic_csr();
  public:

  // uint64 msg_max_isa = 2;
  void clear_msg_max_isa();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_max_isa() const;
  void set_msg_max_isa(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_max_isa() const;
  void _internal_set_msg_max_isa(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 msg_write_mask = 3;
  void clear_msg_write_mask();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_write_mask() const;
  void set_msg_write_mask(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_write_mask() const;
  void _internal_set_msg_write_mask(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:MisaCSR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::BasicCSR* msg_basic_csr_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_max_isa_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_write_mask_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arch_2dstate_2eproto;
};
// -------------------------------------------------------------------

class SatpCSR :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SatpCSR) */ {
 public:
  SatpCSR();
  virtual ~SatpCSR();

  SatpCSR(const SatpCSR& from);
  SatpCSR(SatpCSR&& from) noexcept
    : SatpCSR() {
    *this = ::std::move(from);
  }

  inline SatpCSR& operator=(const SatpCSR& from) {
    CopyFrom(from);
    return *this;
  }
  inline SatpCSR& operator=(SatpCSR&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SatpCSR& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SatpCSR* internal_default_instance() {
    return reinterpret_cast<const SatpCSR*>(
               &_SatpCSR_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SatpCSR& a, SatpCSR& b) {
    a.Swap(&b);
  }
  inline void Swap(SatpCSR* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SatpCSR* New() const final {
    return CreateMaybeMessage<SatpCSR>(nullptr);
  }

  SatpCSR* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SatpCSR>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SatpCSR& from);
  void MergeFrom(const SatpCSR& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SatpCSR* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SatpCSR";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arch_2dstate_2eproto);
    return ::descriptor_table_arch_2dstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgNonvirtSatpCsrFieldNumber = 1,
    kMsgVirtSatpCsrFieldNumber = 2,
  };
  // .BasicCSR msg_nonvirt_satp_csr = 1;
  bool has_msg_nonvirt_satp_csr() const;
  private:
  bool _internal_has_msg_nonvirt_satp_csr() const;
  public:
  void clear_msg_nonvirt_satp_csr();
  const ::BasicCSR& msg_nonvirt_satp_csr() const;
  ::BasicCSR* release_msg_nonvirt_satp_csr();
  ::BasicCSR* mutable_msg_nonvirt_satp_csr();
  void set_allocated_msg_nonvirt_satp_csr(::BasicCSR* msg_nonvirt_satp_csr);
  private:
  const ::BasicCSR& _internal_msg_nonvirt_satp_csr() const;
  ::BasicCSR* _internal_mutable_msg_nonvirt_satp_csr();
  public:

  // .BasicCSR msg_virt_satp_csr = 2;
  bool has_msg_virt_satp_csr() const;
  private:
  bool _internal_has_msg_virt_satp_csr() const;
  public:
  void clear_msg_virt_satp_csr();
  const ::BasicCSR& msg_virt_satp_csr() const;
  ::BasicCSR* release_msg_virt_satp_csr();
  ::BasicCSR* mutable_msg_virt_satp_csr();
  void set_allocated_msg_virt_satp_csr(::BasicCSR* msg_virt_satp_csr);
  private:
  const ::BasicCSR& _internal_msg_virt_satp_csr() const;
  ::BasicCSR* _internal_mutable_msg_virt_satp_csr();
  public:

  // @@protoc_insertion_point(class_scope:SatpCSR)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::BasicCSR* msg_nonvirt_satp_csr_;
  ::BasicCSR* msg_virt_satp_csr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arch_2dstate_2eproto;
};
// -------------------------------------------------------------------

class ArchState :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ArchState) */ {
 public:
  ArchState();
  virtual ~ArchState();

  ArchState(const ArchState& from);
  ArchState(ArchState&& from) noexcept
    : ArchState() {
    *this = ::std::move(from);
  }

  inline ArchState& operator=(const ArchState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArchState& operator=(ArchState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ArchState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArchState* internal_default_instance() {
    return reinterpret_cast<const ArchState*>(
               &_ArchState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ArchState& a, ArchState& b) {
    a.Swap(&b);
  }
  inline void Swap(ArchState* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ArchState* New() const final {
    return CreateMaybeMessage<ArchState>(nullptr);
  }

  ArchState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ArchState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ArchState& from);
  void MergeFrom(const ArchState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArchState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ArchState";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_arch_2dstate_2eproto);
    return ::descriptor_table_arch_2dstate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgMstatushFieldNumber = 2,
    kMsgMisaFieldNumber = 3,
    kMsgSatpFieldNumber = 4,
    kMsgPcFieldNumber = 1,
  };
  // .CSR msg_mstatush = 2;
  bool has_msg_mstatush() const;
  private:
  bool _internal_has_msg_mstatush() const;
  public:
  void clear_msg_mstatush();
  const ::CSR& msg_mstatush() const;
  ::CSR* release_msg_mstatush();
  ::CSR* mutable_msg_mstatush();
  void set_allocated_msg_mstatush(::CSR* msg_mstatush);
  private:
  const ::CSR& _internal_msg_mstatush() const;
  ::CSR* _internal_mutable_msg_mstatush();
  public:

  // .MisaCSR msg_misa = 3;
  bool has_msg_misa() const;
  private:
  bool _internal_has_msg_misa() const;
  public:
  void clear_msg_misa();
  const ::MisaCSR& msg_misa() const;
  ::MisaCSR* release_msg_misa();
  ::MisaCSR* mutable_msg_misa();
  void set_allocated_msg_misa(::MisaCSR* msg_misa);
  private:
  const ::MisaCSR& _internal_msg_misa() const;
  ::MisaCSR* _internal_mutable_msg_misa();
  public:

  // .SatpCSR msg_satp = 4;
  bool has_msg_satp() const;
  private:
  bool _internal_has_msg_satp() const;
  public:
  void clear_msg_satp();
  const ::SatpCSR& msg_satp() const;
  ::SatpCSR* release_msg_satp();
  ::SatpCSR* mutable_msg_satp();
  void set_allocated_msg_satp(::SatpCSR* msg_satp);
  private:
  const ::SatpCSR& _internal_msg_satp() const;
  ::SatpCSR* _internal_mutable_msg_satp();
  public:

  // uint64 msg_pc = 1;
  void clear_msg_pc();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_pc() const;
  void set_msg_pc(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_pc() const;
  void _internal_set_msg_pc(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:ArchState)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::CSR* msg_mstatush_;
  ::MisaCSR* msg_misa_;
  ::SatpCSR* msg_satp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_pc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_arch_2dstate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CSR

// uint64 msg_addr = 1;
inline void CSR::clear_msg_addr() {
  msg_addr_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CSR::_internal_msg_addr() const {
  return msg_addr_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CSR::msg_addr() const {
  // @@protoc_insertion_point(field_get:CSR.msg_addr)
  return _internal_msg_addr();
}
inline void CSR::_internal_set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_addr_ = value;
}
inline void CSR::set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_addr(value);
  // @@protoc_insertion_point(field_set:CSR.msg_addr)
}

// uint32 msg_csr_priv = 2;
inline void CSR::clear_msg_csr_priv() {
  msg_csr_priv_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CSR::_internal_msg_csr_priv() const {
  return msg_csr_priv_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CSR::msg_csr_priv() const {
  // @@protoc_insertion_point(field_get:CSR.msg_csr_priv)
  return _internal_msg_csr_priv();
}
inline void CSR::_internal_set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  msg_csr_priv_ = value;
}
inline void CSR::set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_msg_csr_priv(value);
  // @@protoc_insertion_point(field_set:CSR.msg_csr_priv)
}

// bool msg_csr_read_only = 3;
inline void CSR::clear_msg_csr_read_only() {
  msg_csr_read_only_ = false;
}
inline bool CSR::_internal_msg_csr_read_only() const {
  return msg_csr_read_only_;
}
inline bool CSR::msg_csr_read_only() const {
  // @@protoc_insertion_point(field_get:CSR.msg_csr_read_only)
  return _internal_msg_csr_read_only();
}
inline void CSR::_internal_set_msg_csr_read_only(bool value) {
  
  msg_csr_read_only_ = value;
}
inline void CSR::set_msg_csr_read_only(bool value) {
  _internal_set_msg_csr_read_only(value);
  // @@protoc_insertion_point(field_set:CSR.msg_csr_read_only)
}

// -------------------------------------------------------------------

// BasicCSR

// uint64 msg_addr = 1;
inline void BasicCSR::clear_msg_addr() {
  msg_addr_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BasicCSR::_internal_msg_addr() const {
  return msg_addr_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BasicCSR::msg_addr() const {
  // @@protoc_insertion_point(field_get:BasicCSR.msg_addr)
  return _internal_msg_addr();
}
inline void BasicCSR::_internal_set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_addr_ = value;
}
inline void BasicCSR::set_msg_addr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_addr(value);
  // @@protoc_insertion_point(field_set:BasicCSR.msg_addr)
}

// uint32 msg_csr_priv = 2;
inline void BasicCSR::clear_msg_csr_priv() {
  msg_csr_priv_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 BasicCSR::_internal_msg_csr_priv() const {
  return msg_csr_priv_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 BasicCSR::msg_csr_priv() const {
  // @@protoc_insertion_point(field_get:BasicCSR.msg_csr_priv)
  return _internal_msg_csr_priv();
}
inline void BasicCSR::_internal_set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  msg_csr_priv_ = value;
}
inline void BasicCSR::set_msg_csr_priv(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_msg_csr_priv(value);
  // @@protoc_insertion_point(field_set:BasicCSR.msg_csr_priv)
}

// bool msg_csr_read_only = 3;
inline void BasicCSR::clear_msg_csr_read_only() {
  msg_csr_read_only_ = false;
}
inline bool BasicCSR::_internal_msg_csr_read_only() const {
  return msg_csr_read_only_;
}
inline bool BasicCSR::msg_csr_read_only() const {
  // @@protoc_insertion_point(field_get:BasicCSR.msg_csr_read_only)
  return _internal_msg_csr_read_only();
}
inline void BasicCSR::_internal_set_msg_csr_read_only(bool value) {
  
  msg_csr_read_only_ = value;
}
inline void BasicCSR::set_msg_csr_read_only(bool value) {
  _internal_set_msg_csr_read_only(value);
  // @@protoc_insertion_point(field_set:BasicCSR.msg_csr_read_only)
}

// uint64 msg_val = 4;
inline void BasicCSR::clear_msg_val() {
  msg_val_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BasicCSR::_internal_msg_val() const {
  return msg_val_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 BasicCSR::msg_val() const {
  // @@protoc_insertion_point(field_get:BasicCSR.msg_val)
  return _internal_msg_val();
}
inline void BasicCSR::_internal_set_msg_val(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_val_ = value;
}
inline void BasicCSR::set_msg_val(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_val(value);
  // @@protoc_insertion_point(field_set:BasicCSR.msg_val)
}

// -------------------------------------------------------------------

// MisaCSR

// .BasicCSR msg_basic_csr = 1;
inline bool MisaCSR::_internal_has_msg_basic_csr() const {
  return this != internal_default_instance() && msg_basic_csr_ != nullptr;
}
inline bool MisaCSR::has_msg_basic_csr() const {
  return _internal_has_msg_basic_csr();
}
inline void MisaCSR::clear_msg_basic_csr() {
  if (GetArenaNoVirtual() == nullptr && msg_basic_csr_ != nullptr) {
    delete msg_basic_csr_;
  }
  msg_basic_csr_ = nullptr;
}
inline const ::BasicCSR& MisaCSR::_internal_msg_basic_csr() const {
  const ::BasicCSR* p = msg_basic_csr_;
  return p != nullptr ? *p : *reinterpret_cast<const ::BasicCSR*>(
      &::_BasicCSR_default_instance_);
}
inline const ::BasicCSR& MisaCSR::msg_basic_csr() const {
  // @@protoc_insertion_point(field_get:MisaCSR.msg_basic_csr)
  return _internal_msg_basic_csr();
}
inline ::BasicCSR* MisaCSR::release_msg_basic_csr() {
  // @@protoc_insertion_point(field_release:MisaCSR.msg_basic_csr)
  
  ::BasicCSR* temp = msg_basic_csr_;
  msg_basic_csr_ = nullptr;
  return temp;
}
inline ::BasicCSR* MisaCSR::_internal_mutable_msg_basic_csr() {
  
  if (msg_basic_csr_ == nullptr) {
    auto* p = CreateMaybeMessage<::BasicCSR>(GetArenaNoVirtual());
    msg_basic_csr_ = p;
  }
  return msg_basic_csr_;
}
inline ::BasicCSR* MisaCSR::mutable_msg_basic_csr() {
  // @@protoc_insertion_point(field_mutable:MisaCSR.msg_basic_csr)
  return _internal_mutable_msg_basic_csr();
}
inline void MisaCSR::set_allocated_msg_basic_csr(::BasicCSR* msg_basic_csr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_basic_csr_;
  }
  if (msg_basic_csr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_basic_csr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_basic_csr, submessage_arena);
    }
    
  } else {
    
  }
  msg_basic_csr_ = msg_basic_csr;
  // @@protoc_insertion_point(field_set_allocated:MisaCSR.msg_basic_csr)
}

// uint64 msg_max_isa = 2;
inline void MisaCSR::clear_msg_max_isa() {
  msg_max_isa_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MisaCSR::_internal_msg_max_isa() const {
  return msg_max_isa_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MisaCSR::msg_max_isa() const {
  // @@protoc_insertion_point(field_get:MisaCSR.msg_max_isa)
  return _internal_msg_max_isa();
}
inline void MisaCSR::_internal_set_msg_max_isa(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_max_isa_ = value;
}
inline void MisaCSR::set_msg_max_isa(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_max_isa(value);
  // @@protoc_insertion_point(field_set:MisaCSR.msg_max_isa)
}

// uint64 msg_write_mask = 3;
inline void MisaCSR::clear_msg_write_mask() {
  msg_write_mask_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MisaCSR::_internal_msg_write_mask() const {
  return msg_write_mask_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MisaCSR::msg_write_mask() const {
  // @@protoc_insertion_point(field_get:MisaCSR.msg_write_mask)
  return _internal_msg_write_mask();
}
inline void MisaCSR::_internal_set_msg_write_mask(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_write_mask_ = value;
}
inline void MisaCSR::set_msg_write_mask(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_write_mask(value);
  // @@protoc_insertion_point(field_set:MisaCSR.msg_write_mask)
}

// -------------------------------------------------------------------

// SatpCSR

// .BasicCSR msg_nonvirt_satp_csr = 1;
inline bool SatpCSR::_internal_has_msg_nonvirt_satp_csr() const {
  return this != internal_default_instance() && msg_nonvirt_satp_csr_ != nullptr;
}
inline bool SatpCSR::has_msg_nonvirt_satp_csr() const {
  return _internal_has_msg_nonvirt_satp_csr();
}
inline void SatpCSR::clear_msg_nonvirt_satp_csr() {
  if (GetArenaNoVirtual() == nullptr && msg_nonvirt_satp_csr_ != nullptr) {
    delete msg_nonvirt_satp_csr_;
  }
  msg_nonvirt_satp_csr_ = nullptr;
}
inline const ::BasicCSR& SatpCSR::_internal_msg_nonvirt_satp_csr() const {
  const ::BasicCSR* p = msg_nonvirt_satp_csr_;
  return p != nullptr ? *p : *reinterpret_cast<const ::BasicCSR*>(
      &::_BasicCSR_default_instance_);
}
inline const ::BasicCSR& SatpCSR::msg_nonvirt_satp_csr() const {
  // @@protoc_insertion_point(field_get:SatpCSR.msg_nonvirt_satp_csr)
  return _internal_msg_nonvirt_satp_csr();
}
inline ::BasicCSR* SatpCSR::release_msg_nonvirt_satp_csr() {
  // @@protoc_insertion_point(field_release:SatpCSR.msg_nonvirt_satp_csr)
  
  ::BasicCSR* temp = msg_nonvirt_satp_csr_;
  msg_nonvirt_satp_csr_ = nullptr;
  return temp;
}
inline ::BasicCSR* SatpCSR::_internal_mutable_msg_nonvirt_satp_csr() {
  
  if (msg_nonvirt_satp_csr_ == nullptr) {
    auto* p = CreateMaybeMessage<::BasicCSR>(GetArenaNoVirtual());
    msg_nonvirt_satp_csr_ = p;
  }
  return msg_nonvirt_satp_csr_;
}
inline ::BasicCSR* SatpCSR::mutable_msg_nonvirt_satp_csr() {
  // @@protoc_insertion_point(field_mutable:SatpCSR.msg_nonvirt_satp_csr)
  return _internal_mutable_msg_nonvirt_satp_csr();
}
inline void SatpCSR::set_allocated_msg_nonvirt_satp_csr(::BasicCSR* msg_nonvirt_satp_csr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_nonvirt_satp_csr_;
  }
  if (msg_nonvirt_satp_csr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_nonvirt_satp_csr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_nonvirt_satp_csr, submessage_arena);
    }
    
  } else {
    
  }
  msg_nonvirt_satp_csr_ = msg_nonvirt_satp_csr;
  // @@protoc_insertion_point(field_set_allocated:SatpCSR.msg_nonvirt_satp_csr)
}

// .BasicCSR msg_virt_satp_csr = 2;
inline bool SatpCSR::_internal_has_msg_virt_satp_csr() const {
  return this != internal_default_instance() && msg_virt_satp_csr_ != nullptr;
}
inline bool SatpCSR::has_msg_virt_satp_csr() const {
  return _internal_has_msg_virt_satp_csr();
}
inline void SatpCSR::clear_msg_virt_satp_csr() {
  if (GetArenaNoVirtual() == nullptr && msg_virt_satp_csr_ != nullptr) {
    delete msg_virt_satp_csr_;
  }
  msg_virt_satp_csr_ = nullptr;
}
inline const ::BasicCSR& SatpCSR::_internal_msg_virt_satp_csr() const {
  const ::BasicCSR* p = msg_virt_satp_csr_;
  return p != nullptr ? *p : *reinterpret_cast<const ::BasicCSR*>(
      &::_BasicCSR_default_instance_);
}
inline const ::BasicCSR& SatpCSR::msg_virt_satp_csr() const {
  // @@protoc_insertion_point(field_get:SatpCSR.msg_virt_satp_csr)
  return _internal_msg_virt_satp_csr();
}
inline ::BasicCSR* SatpCSR::release_msg_virt_satp_csr() {
  // @@protoc_insertion_point(field_release:SatpCSR.msg_virt_satp_csr)
  
  ::BasicCSR* temp = msg_virt_satp_csr_;
  msg_virt_satp_csr_ = nullptr;
  return temp;
}
inline ::BasicCSR* SatpCSR::_internal_mutable_msg_virt_satp_csr() {
  
  if (msg_virt_satp_csr_ == nullptr) {
    auto* p = CreateMaybeMessage<::BasicCSR>(GetArenaNoVirtual());
    msg_virt_satp_csr_ = p;
  }
  return msg_virt_satp_csr_;
}
inline ::BasicCSR* SatpCSR::mutable_msg_virt_satp_csr() {
  // @@protoc_insertion_point(field_mutable:SatpCSR.msg_virt_satp_csr)
  return _internal_mutable_msg_virt_satp_csr();
}
inline void SatpCSR::set_allocated_msg_virt_satp_csr(::BasicCSR* msg_virt_satp_csr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_virt_satp_csr_;
  }
  if (msg_virt_satp_csr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_virt_satp_csr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_virt_satp_csr, submessage_arena);
    }
    
  } else {
    
  }
  msg_virt_satp_csr_ = msg_virt_satp_csr;
  // @@protoc_insertion_point(field_set_allocated:SatpCSR.msg_virt_satp_csr)
}

// -------------------------------------------------------------------

// ArchState

// uint64 msg_pc = 1;
inline void ArchState::clear_msg_pc() {
  msg_pc_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ArchState::_internal_msg_pc() const {
  return msg_pc_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ArchState::msg_pc() const {
  // @@protoc_insertion_point(field_get:ArchState.msg_pc)
  return _internal_msg_pc();
}
inline void ArchState::_internal_set_msg_pc(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_pc_ = value;
}
inline void ArchState::set_msg_pc(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_pc(value);
  // @@protoc_insertion_point(field_set:ArchState.msg_pc)
}

// .CSR msg_mstatush = 2;
inline bool ArchState::_internal_has_msg_mstatush() const {
  return this != internal_default_instance() && msg_mstatush_ != nullptr;
}
inline bool ArchState::has_msg_mstatush() const {
  return _internal_has_msg_mstatush();
}
inline void ArchState::clear_msg_mstatush() {
  if (GetArenaNoVirtual() == nullptr && msg_mstatush_ != nullptr) {
    delete msg_mstatush_;
  }
  msg_mstatush_ = nullptr;
}
inline const ::CSR& ArchState::_internal_msg_mstatush() const {
  const ::CSR* p = msg_mstatush_;
  return p != nullptr ? *p : *reinterpret_cast<const ::CSR*>(
      &::_CSR_default_instance_);
}
inline const ::CSR& ArchState::msg_mstatush() const {
  // @@protoc_insertion_point(field_get:ArchState.msg_mstatush)
  return _internal_msg_mstatush();
}
inline ::CSR* ArchState::release_msg_mstatush() {
  // @@protoc_insertion_point(field_release:ArchState.msg_mstatush)
  
  ::CSR* temp = msg_mstatush_;
  msg_mstatush_ = nullptr;
  return temp;
}
inline ::CSR* ArchState::_internal_mutable_msg_mstatush() {
  
  if (msg_mstatush_ == nullptr) {
    auto* p = CreateMaybeMessage<::CSR>(GetArenaNoVirtual());
    msg_mstatush_ = p;
  }
  return msg_mstatush_;
}
inline ::CSR* ArchState::mutable_msg_mstatush() {
  // @@protoc_insertion_point(field_mutable:ArchState.msg_mstatush)
  return _internal_mutable_msg_mstatush();
}
inline void ArchState::set_allocated_msg_mstatush(::CSR* msg_mstatush) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_mstatush_;
  }
  if (msg_mstatush) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_mstatush = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_mstatush, submessage_arena);
    }
    
  } else {
    
  }
  msg_mstatush_ = msg_mstatush;
  // @@protoc_insertion_point(field_set_allocated:ArchState.msg_mstatush)
}

// .MisaCSR msg_misa = 3;
inline bool ArchState::_internal_has_msg_misa() const {
  return this != internal_default_instance() && msg_misa_ != nullptr;
}
inline bool ArchState::has_msg_misa() const {
  return _internal_has_msg_misa();
}
inline void ArchState::clear_msg_misa() {
  if (GetArenaNoVirtual() == nullptr && msg_misa_ != nullptr) {
    delete msg_misa_;
  }
  msg_misa_ = nullptr;
}
inline const ::MisaCSR& ArchState::_internal_msg_misa() const {
  const ::MisaCSR* p = msg_misa_;
  return p != nullptr ? *p : *reinterpret_cast<const ::MisaCSR*>(
      &::_MisaCSR_default_instance_);
}
inline const ::MisaCSR& ArchState::msg_misa() const {
  // @@protoc_insertion_point(field_get:ArchState.msg_misa)
  return _internal_msg_misa();
}
inline ::MisaCSR* ArchState::release_msg_misa() {
  // @@protoc_insertion_point(field_release:ArchState.msg_misa)
  
  ::MisaCSR* temp = msg_misa_;
  msg_misa_ = nullptr;
  return temp;
}
inline ::MisaCSR* ArchState::_internal_mutable_msg_misa() {
  
  if (msg_misa_ == nullptr) {
    auto* p = CreateMaybeMessage<::MisaCSR>(GetArenaNoVirtual());
    msg_misa_ = p;
  }
  return msg_misa_;
}
inline ::MisaCSR* ArchState::mutable_msg_misa() {
  // @@protoc_insertion_point(field_mutable:ArchState.msg_misa)
  return _internal_mutable_msg_misa();
}
inline void ArchState::set_allocated_msg_misa(::MisaCSR* msg_misa) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_misa_;
  }
  if (msg_misa) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_misa = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_misa, submessage_arena);
    }
    
  } else {
    
  }
  msg_misa_ = msg_misa;
  // @@protoc_insertion_point(field_set_allocated:ArchState.msg_misa)
}

// .SatpCSR msg_satp = 4;
inline bool ArchState::_internal_has_msg_satp() const {
  return this != internal_default_instance() && msg_satp_ != nullptr;
}
inline bool ArchState::has_msg_satp() const {
  return _internal_has_msg_satp();
}
inline void ArchState::clear_msg_satp() {
  if (GetArenaNoVirtual() == nullptr && msg_satp_ != nullptr) {
    delete msg_satp_;
  }
  msg_satp_ = nullptr;
}
inline const ::SatpCSR& ArchState::_internal_msg_satp() const {
  const ::SatpCSR* p = msg_satp_;
  return p != nullptr ? *p : *reinterpret_cast<const ::SatpCSR*>(
      &::_SatpCSR_default_instance_);
}
inline const ::SatpCSR& ArchState::msg_satp() const {
  // @@protoc_insertion_point(field_get:ArchState.msg_satp)
  return _internal_msg_satp();
}
inline ::SatpCSR* ArchState::release_msg_satp() {
  // @@protoc_insertion_point(field_release:ArchState.msg_satp)
  
  ::SatpCSR* temp = msg_satp_;
  msg_satp_ = nullptr;
  return temp;
}
inline ::SatpCSR* ArchState::_internal_mutable_msg_satp() {
  
  if (msg_satp_ == nullptr) {
    auto* p = CreateMaybeMessage<::SatpCSR>(GetArenaNoVirtual());
    msg_satp_ = p;
  }
  return msg_satp_;
}
inline ::SatpCSR* ArchState::mutable_msg_satp() {
  // @@protoc_insertion_point(field_mutable:ArchState.msg_satp)
  return _internal_mutable_msg_satp();
}
inline void ArchState::set_allocated_msg_satp(::SatpCSR* msg_satp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msg_satp_;
  }
  if (msg_satp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg_satp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg_satp, submessage_arena);
    }
    
  } else {
    
  }
  msg_satp_ = msg_satp;
  // @@protoc_insertion_point(field_set_allocated:ArchState.msg_satp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_arch_2dstate_2eproto
